export const stubSearchIndexCollection = [
  {
    searchId: "TESTSEARCH1",
    abn: "91111111110",
    businessName: "JG Farms",
    email: "john@gmail.com",
    firstName: "John",
    lastName: "Grant",
    fullName: "John Grant",
    orgId: "A0000001",
    pbuId: "PBU0000000001",
    pbuName: "John Grant Unit",
    stateCode: "VIC",
    tradingName: "",
  },
  {
    searchId: "TESTSEARCH2",
    abn: "11111111112",
    businessName: "D'Anthony Fruit Growers",
    email: "john.danthony@fruitgrower.com",
    firstName: "John",
    lastName: "D'Anthony",
    fullName: "John D'Anthony",
    orgId: "A00000002",
    pbuId: "PBU0000000002",
    pbuName: "HR Department",
    stateCode: "NSW",
    tradingName: "",
  },
  {
    searchId: "TESTSEARCH3",
    abn: "11111111113",
    businessName: "John Papa Farm",
    email: "office@hello.com",
    firstName: "John",
    lastName: "Papa",
    fullName: "John Papa",
    orgId: "A00000003",
    pbuId: "PBU0000000234",
    pbuName: "John PAPA & Sons",
    stateCode: "SA",
    tradingName: "John Papa & Sons",
  },
];

export default stubSearchIndexCollection;
