export const stubPBUDetailCollection = [
  {
    _id: 1,
    pbuId: "PBU0000000001",
    adminComment: "This is test admin",
    appId: "APP0000000001",
    auditComment: "The audit is pretty good",
    auditStatus: "PENDING",
    certComment: "Not quite certified yet",
    certStatus: "UNCERTIFIED",
    controlledSiteLimit: 2,
    description: "",
    employmentProfile: {
      useslabourHire: true,
      seasonLength: 3,
      usesPieceRate: true,
      hiresESL: true,
      hiresTempVisa: true,
      hiresMinor: false,
      workersPerPeak: 25,
      accommTransportProvided: true,
    },
    name: "John Grant Unit",
    orgId: "A0000001",
    orgName: "JG Farms",
    orgStatus: "ACTIVE",
    osaComment: "Completed",
    osaFeedback: "/file/path",
    osaPassed: true,
    osaStatus: "COMPLETE",
    paymentPlan: "PBUSITECOST",
    physicalAddress: {
      address: "Helloville",
      locality: "Thorpdale",
      stateCode: "VIC",
      postcode: "3835",
    },
    subtypes: ["GROWER", "PACKER"],
    trainingComment: "Should ask them to setup ASAP",
    trainingQuota: 0,
    trainingStatus: "PENDING",
    controlledSites: [
      {
        siteId: "SITEINTERNAL0001",
        publicSiteId: "SITE0001",
        name: "John's first site",
        address: {
          address: "Helloville",
          locality: "Thorpdale",
          stateCode: "VIC",
          postcode: "3835",
        },
        auditStatus: "PENDING",
        certStatus: "",
      },
      {
        siteId: "SITEINTERNAL0002",
        publicSiteId: "SITE0002",
        name: "John's second farm",
        address: {
          address: "2 One St",
          locality: "Heathcote",
          stateCode: "VIC",
          postcode: "3833",
        },
      },
    ],
    syncDate: new Date("2020-07-01T05:12:00.432Z"),
  },
  {
    _id: 2,
    pbuId: "PBU0000000002",
    adminComment: "",
    appId: "APP123412341",
    auditComment: "",
    auditStatus: "PENDING",
    certComment: "",
    certStatus: "UNCERTIFIED",
    controlledSiteLimit: 1,
    description: "",
    employmentProfile: {
      useslabourHire: true,
      seasonLength: 4,
      usesPieceRate: true,
      hiresESL: false,
      hiresTempVisa: false,
      hiresMinor: false,
      workersPerPeak: 32,
      accommTransportProvided: true,
    },
    name: "John D'Anthony",
    orgId: "A00000002",
    orgName: "D'Anthony Fruit Growers",
    orgStatus: "ACTIVE",
    osaComment: "",
    osaFeedback: null,
    osaPassed: false,
    osaStatus: "PENDING",
    paymentPlan: "PBUSITECOST",
    physicalAddress: {
      address: "Rivierra Rd",
      locality: "Canowindra",
      stateCode: "NSW",
      postcode: "2804",
    },
    subtypes: ["GROWER"],
    trainingComment: "",
    trainingQuota: 1,
    trainingStatus: "PENDING",
    controlledSites: [
      {
        siteId: "SITEINTERNAL0003",
        publicSiteId: "SITE0003",
        name: "Happy Farm",
        address: {
          address: "Rivierra Rd",
          locality: "Canowindra",
          stateCode: "NSW",
          postcode: "2804",
        },
        auditStatus: "PENDING",
        certStatus: "",
      },
    ],
    syncDate: new Date("2020-07-01T05:12:00.432Z"),
  },
  {
    _id: 3,
    pbuId: "PBU0000000234",
    adminComment: "",
    appId: "0DD072A0E0004B27BA288550B748F5A3",
    auditComment: "",
    auditStatus: "COMPLETE-PARTIAL",
    certComment: "",
    certStatus: "CERTIFIED",
    controlledSiteLimit: 3,
    description: "",
    employmentProfile: {
      useslabourHire: true,
      seasonLength: 4,
      usesPieceRate: true,
      hiresESL: false,
      hiresTempVisa: false,
      hiresMinor: false,
      workersPerPeak: 32,
      accommTransportProvided: true,
    },
    name: "John PAPA & Sons",
    orgId: "A00000003",
    orgName: "John Papa Farm",
    orgStatus: "ACTIVE",
    osaComment: "",
    osaFeedback: "/file/something.pdf",
    osaPassed: true,
    osaStatus: "COMPLETE",
    paymentPlan: "PBUSITECOST",
    physicalAddress: {
      address: "1 Test Dr",
      locality: "Hay Valley",
      stateCode: "SA",
      postcode: "5252",
    },
    subtypes: ["GROWER", "WHOLESALE"],
    trainingComment: "",
    trainingQuota: 0,
    trainingStatus: "COMPLETE",
    controlledSites: [
      {
        siteId: "SITEINTERNAL0005",
        publicSiteId: "SITE0004",
        name: "Happy Farm",
        address: {
          address: "1 Test Dr",
          locality: "Hay Valley",
          stateCode: "SA",
          postcode: "5252",
        },
        auditStatus: "COMPLETE",
        certStatus: "",
      },
      {
        siteId: "SITEINTERNAL0006",
        publicSiteId: "SITE0005",
        name: "Happy Farm 2",
        address: {
          address: "2 Test Dr",
          locality: "Hay Valley",
          stateCode: "SA",
          postcode: "5252",
        },
        auditStatus: "COMPLETE",
        certStatus: "",
      },
      {
        siteId: "SITEINTERNAL0007",
        publicSiteId: "SITE0006",
        name: "Happy Farm 3",
        address: {
          address: "1 Eden St",
          locality: "Bundaberg",
          stateCode: "QLD",
          postcode: "4173",
        },
        auditStatus: "PENDING",
        certStatus: "",
      },
    ],
    syncDate: new Date("2020-07-01T05:12:00.432Z"),
  },
];
